- name: Run module on local host
  hosts: localhost
  tasks:
  - name: Create Identity in Keyfactor
    keyfactor_identity:
      name: "KEYFACTOR\\Test"
      state: 'present'
  - name: Create a Role in Keyfactor
    keyfactor_role:
      name: "AnsibleTestRole"
      description: "AnsibleTestRoleDescription"
      state: 'present'
      permissions:
        - 'APIRead'
      identities: 
        - "KEYFACTOR\\Test"
  - name: Create a Metadata Field in Keyfactor
    keyfactor_metadata_fields:
      name: "PodName"
      description: "Pod Name"
      state: "present"
      allow_api: true
      data_type: 1
  - name: Ensure Metadata Field does not exist in Keyfactor
    keyfactor_metadata_fields:
      name: "AnsibleTestField"
      state: "absent"
      data_type: 1